// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/BigDwarf/testci/internal/service/cache"
	"github.com/BigDwarf/testci/internal/service/satellite"
	"sync"
	"time"
)

// Ensure, that CacheMock does implement satellite.Cache.
// If this is not the case, regenerate this file with moq.
var _ satellite.Cache[cache.Cacheable] = &CacheMock[cache.Cacheable]{}

// CacheMock is a mock implementation of satellite.Cache.
//
//	func TestSomethingThatUsesCache(t *testing.T) {
//
//		// make and configure a mocked satellite.Cache
//		mockedCache := &CacheMock{
//			GetFunc: func(ctx context.Context, key string, destination T) error {
//				panic("mock out the Get method")
//			},
//			SetFunc: func(ctx context.Context, key string, value T, expiration time.Duration) error {
//				panic("mock out the Set method")
//			},
//		}
//
//		// use mockedCache in code that requires satellite.Cache
//		// and then make assertions.
//
//	}
type CacheMock[T cache.Cacheable] struct {
	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, key string, destination T) error

	// SetFunc mocks the Set method.
	SetFunc func(ctx context.Context, key string, value T, expiration time.Duration) error

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
			// Destination is the destination argument value.
			Destination T
		}
		// Set holds details about calls to the Set method.
		Set []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
			// Value is the value argument value.
			Value T
			// Expiration is the expiration argument value.
			Expiration time.Duration
		}
	}
	lockGet sync.RWMutex
	lockSet sync.RWMutex
}

// Get calls GetFunc.
func (mock *CacheMock[T]) Get(ctx context.Context, key string, destination T) error {
	if mock.GetFunc == nil {
		panic("CacheMock.GetFunc: method is nil but Cache.Get was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Key         string
		Destination T
	}{
		Ctx:         ctx,
		Key:         key,
		Destination: destination,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, key, destination)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedCache.GetCalls())
func (mock *CacheMock[T]) GetCalls() []struct {
	Ctx         context.Context
	Key         string
	Destination T
} {
	var calls []struct {
		Ctx         context.Context
		Key         string
		Destination T
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// Set calls SetFunc.
func (mock *CacheMock[T]) Set(ctx context.Context, key string, value T, expiration time.Duration) error {
	if mock.SetFunc == nil {
		panic("CacheMock.SetFunc: method is nil but Cache.Set was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		Key        string
		Value      T
		Expiration time.Duration
	}{
		Ctx:        ctx,
		Key:        key,
		Value:      value,
		Expiration: expiration,
	}
	mock.lockSet.Lock()
	mock.calls.Set = append(mock.calls.Set, callInfo)
	mock.lockSet.Unlock()
	return mock.SetFunc(ctx, key, value, expiration)
}

// SetCalls gets all the calls that were made to Set.
// Check the length with:
//
//	len(mockedCache.SetCalls())
func (mock *CacheMock[T]) SetCalls() []struct {
	Ctx        context.Context
	Key        string
	Value      T
	Expiration time.Duration
} {
	var calls []struct {
		Ctx        context.Context
		Key        string
		Value      T
		Expiration time.Duration
	}
	mock.lockSet.RLock()
	calls = mock.calls.Set
	mock.lockSet.RUnlock()
	return calls
}
