// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/BigDwarf/testci/internal/model"
	"github.com/BigDwarf/testci/internal/service/satellite"
	"sync"
)

// Ensure, that RepositoryMock does implement satellite.Repository.
// If this is not the case, regenerate this file with moq.
var _ satellite.Repository = &RepositoryMock{}

// RepositoryMock is a mock implementation of satellite.Repository.
//
//	func TestSomethingThatUsesRepository(t *testing.T) {
//
//		// make and configure a mocked satellite.Repository
//		mockedRepository := &RepositoryMock{
//			CreateFunc: func(ctx context.Context, s model.Satellite) error {
//				panic("mock out the Create method")
//			},
//			GetByNameFunc: func(ctx context.Context, name string) (*model.Satellite, error) {
//				panic("mock out the GetByName method")
//			},
//		}
//
//		// use mockedRepository in code that requires satellite.Repository
//		// and then make assertions.
//
//	}
type RepositoryMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, s model.Satellite) error

	// GetByNameFunc mocks the GetByName method.
	GetByNameFunc func(ctx context.Context, name string) (*model.Satellite, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// S is the s argument value.
			S model.Satellite
		}
		// GetByName holds details about calls to the GetByName method.
		GetByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
		}
	}
	lockCreate    sync.RWMutex
	lockGetByName sync.RWMutex
}

// Create calls CreateFunc.
func (mock *RepositoryMock) Create(ctx context.Context, s model.Satellite) error {
	if mock.CreateFunc == nil {
		panic("RepositoryMock.CreateFunc: method is nil but Repository.Create was just called")
	}
	callInfo := struct {
		Ctx context.Context
		S   model.Satellite
	}{
		Ctx: ctx,
		S:   s,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, s)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedRepository.CreateCalls())
func (mock *RepositoryMock) CreateCalls() []struct {
	Ctx context.Context
	S   model.Satellite
} {
	var calls []struct {
		Ctx context.Context
		S   model.Satellite
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// GetByName calls GetByNameFunc.
func (mock *RepositoryMock) GetByName(ctx context.Context, name string) (*model.Satellite, error) {
	if mock.GetByNameFunc == nil {
		panic("RepositoryMock.GetByNameFunc: method is nil but Repository.GetByName was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
	}{
		Ctx:  ctx,
		Name: name,
	}
	mock.lockGetByName.Lock()
	mock.calls.GetByName = append(mock.calls.GetByName, callInfo)
	mock.lockGetByName.Unlock()
	return mock.GetByNameFunc(ctx, name)
}

// GetByNameCalls gets all the calls that were made to GetByName.
// Check the length with:
//
//	len(mockedRepository.GetByNameCalls())
func (mock *RepositoryMock) GetByNameCalls() []struct {
	Ctx  context.Context
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
	}
	mock.lockGetByName.RLock()
	calls = mock.calls.GetByName
	mock.lockGetByName.RUnlock()
	return calls
}
